invoice/urls.py
from django.conf.urls import  url
from django.contrib import admin
from invoice import views
# from .views import GeneratePDF



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^customers$', views.customer_list, name='customer_list'),
    url(r'^customer/new$', views.customer_create, name='customer_create'),
    url(r'^customer/detail/(?P<pk>\d+)/$', views.customer_detail, name='customer_detail'),
    url(r'^products$', views.product_list, name='product_list'),
    url(r'^product/new$', views.product_create, name='product_create'),
    url(r'^product/detail/(?P<pk>\d+)/$', views.product_detail, name='product_detail'),
    url(r'^customer/invoice/(?P<id>\d+)/$', views.invoicebycustomerid, name='invoicebycustomerid'),
    url(r'^invoices', views.invoice_list, name = 'invoice_list'),
	url(r'^new$', views.invoice_create, name = 'invoice_create'),
	url(r'^detail/(?P<id>\d+)/$', views.invoice_detail, name = 'invoice_detail'),
    url(r'^pdf/(?P<id>\d+)/$', views.htmltopdf , name = 'htmltopdf'), 
    # url(r'^sendemail/(?P<id>\d+)/$', views.send_email , name = 'send_email'), 




]

supermarketsystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^invoice/', include('invoice.urls', namespace='invoice')),
    url(r'^$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),

]

invoice/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.validators import MinValueValidator


# Create your models here.
class Customer(models.Model):   
    name = models.CharField(max_length = 200)
    phone = models.IntegerField()   
    address = models.CharField(max_length = 200)  
    email= models.EmailField(max_length = 254) 
    block_status= models.BooleanField(default=False) 
    # class Meta:  
    #     db_table = "customer"  
    
    def __str__(self):
        return self.name
   


class Product(models.Model):
    name = models.CharField(max_length = 200)
    price = models.IntegerField()   
    quantity = models.PositiveIntegerField(default=5, validators=[MinValueValidator(0)])   
    # class Meta:  
    #     db_table = "product"   
    def __str__(self):
        return self.name


class Invoice(models.Model):
    shipping_address = models.CharField(max_length = 200)  
    created_at= models.DateTimeField('created_at')
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE)
    product=models.ManyToManyField('Product')
    # class Meta:  
    #     db_table = "invoice"  
    def __str__(self):
        return self.name

invoice/forms.py
from django import forms  
from invoice.models import Customer,Invoice,Product

class CustomerForm(forms.ModelForm):  
    class Meta:  
        model = Customer 
        fields = "__all__"

class ProductForm(forms.ModelForm):
    class Meta:
        model= Product
        fields = "__all__"

class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = "__all__"

        

invoice/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect, get_object_or_404
from .models import Customer,Invoice,Product
from .forms import CustomerForm,InvoiceForm,ProductForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
#rendering html to pdf
from django.views.generic import View
from .utils import render_to_pdf 
from django.template.loader import get_template
#send email
from supermarketsystem.settings import EMAIL_HOST_USER
from django.core.mail import send_mail



@login_required(login_url='/')
def customer_list(request, template_name='customer/customer_list.html'):
    customers = Customer.objects.all()
    data = {}
    data['object_list'] = customers
    return render(request, template_name, data)

@login_required(login_url='/')
def customer_create(request, template_name='customer/customer_form.html'):
    form = CustomerForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('invoice:customer_list')
    return render(request, template_name, {'form': form})

@login_required(login_url='/')
def customer_detail(request, pk, template_name='customer/customer_detail.html'):
    customer= get_object_or_404(Customer, pk=pk)    
    return render(request, template_name, {'object':customer})
   

@login_required(login_url='/')
def product_list(request, template_name='product/product_list.html'):
    products = Product.objects.all()
    data = {}
    data['object_list'] = products
    return render(request, template_name, data)

@login_required(login_url='/')
def product_create(request, template_name='product/product_form.html'):
    form = ProductForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('invoice:product_list')
    return render(request, template_name, {'form': form})

@login_required(login_url='/')
def product_detail(request, pk, template_name='product/product_detail.html'):
    product= get_object_or_404(Product, pk=pk)    
    return render(request, template_name, {'object':product})


@login_required(login_url='/')
def invoice_list(request):
	invoices = Invoice.objects.all()
	return render(request, 'invoice/invoice_list.html', { 'invoices': invoices })


@login_required(login_url='/')
def invoice_create(request, template_name='invoice/invoice_form.html'):
    form = InvoiceForm(request.POST or None)
    if form.is_valid():
        form.save()
        subject = 'Purchase Confirmation'
        message = 'Your Invoice Data: ' + str(form.cleaned_data)
        recepient = 'yasmina.khaled96@gmail.com'
        # recepient = str(form.cleaned_data.get("customer"))
        send_mail(subject, message, EMAIL_HOST_USER, [recepient], fail_silently = False)
        return redirect('invoice:invoice_list')
    return render(request, template_name, {'form': form})

@login_required(login_url='/')
def invoice_detail(request, id):
	invoice = Invoice.objects.get(id = id)
	return render(request, 'invoice/invoice_detail.html', { 'invoice': invoice })
 

@login_required(login_url='/')
def invoicebycustomerid(request, id):
    customer = Customer.objects.get(id = id)
    invoices = Invoice.objects.filter(customer = customer)
    return render(request, 'invoice/invoice_list.html', { 'invoices': invoices })


@login_required(login_url='/')
def htmltopdf(request, id, *args, **kwargs):
        invoice = Invoice.objects.get(id = id)
        template = get_template('invoice/invoice_detail.html')
        html = template.render({'invoice': invoice })
        pdf = render_to_pdf('invoice/invoice_detail.html', {'invoice': invoice })
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Invoice_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")

invoice/templates/customer/customer_detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Customer Details</title>
  </head>
  <body>
<form>
   
   
    <div class="row">
        <label for="Name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" id="name" class="form-control-plaintext" value="{{ object.name }}" readonly>
        </div>
    </div>
    <div class="row">
        <label for="phone" class="col-sm-2 col-form-label">Phone</label>
        <div class="col-sm-10">
            <input type="text" id="phone" class="form-control-plaintext" value=" {{ object.phone }}" readonly>
        </div>
    </div>
    <div class="row">
        <label for="email" class="col-sm-2 col-form-label">Email</label>
        <div class="col-sm-10">
            <input type="text" id="email" class="form-control-plaintext" value="{{ object.email }}" readonly>
        </div>
    </div>
    <div class="row">
        <label for="address" class="col-sm-2 col-form-label">Address</label>
        <div class="col-sm-10">
            <input type="text" id="address" class="form-control-plaintext" value="{{ object.address }}" readonly>
        </div>
    </div>
    <div class="row">
        <label for="block_status" class="col-sm-2 col-form-label">Block Status</label>
        <div class="col-sm-10">
            <input type="text" id="block_status" class="form-control-plaintext" value="{{ object.block_status }}" readonly>
        </div>
    </div> 
   
   
</form>
<a href="{% url "invoice:customer_list" %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">All customers</a>
</body>
</html>

invoice/templates/customer/customer_form.html
<!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
        <title>Add a new customer</title>
      </head>
      <body>
        <div class="container">
          <h3 class="m-6 font-weight-bold text-primary">Insert Data for a new customer</h3>
          <form  method="post">{% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Submit" />
            <a href="{% url "invoice:customer_list" %}">All customers</a>

          </form>
        </div>
      </body>
    </html>

invoice/templates/customer/customer_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Customers</title>
  </head>
  <body>
    <div class="card shadow mb-4">
      <div class="card-header py-3">
              <h2 class="m-6 font-weight-bold text-primary">Customers Management</h2>
              <a href="{% url "invoice:customer_create" %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Create a new customer account</a>
              <a href="{% url 'logout' %}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Logout</a>
  
  
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Address</th>
                                    <td>Block Status</td> 
                                    <th>View Details</th>
                                    <th>His invoices</th>
                                    </tr>
                                    </thead>
                  
                               <tbody>
                                {% for customer in object_list %}    
                                <tr>
                                <td>{{ customer.id }}</td>  
                                <td>{{ customer.name }}</td>  
                                <td>{{ customer.email }}</td>  
                                <td>{{ customer.phone }}</td>  
                                <td>{{ customer.address }}</td>  
                                <td>{{ customer.block_status}}</td> 
                                <td><a href="{% url "invoice:customer_detail" customer.id %}">Details</a></td>
                                 <td><a href="{% url "invoice:invoicebycustomerid" customer.id %}">Customer Invoices</a></td>
                                    </tr>
                                {% endfor %}
                  </tbody>
                        </table>
                        <a href="{% url "invoice:invoice_list" %}">All Invoices</a>
                        <br>
                        <a href="{% url "invoice:product_list" %}">All products</a>

              </div>
            </div>
          </div>                    
        </body>
        </html>

       

invoice/templates/invoice/invoice_detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Invoices</title>
  </head>
  <body>
<form>
   
    <div class="row">
        <label for="id" class="col-sm-2 col-form-label">ID</label>
        <div class="col-sm-10">
            <input type="text" id="id" class="form-control-plaintext" value="{{ invoice.id }}" readonly>
        </div>
    </div>
    <div class="row">
        <label for="shipping_address" class="col-sm-2 col-form-label">Shipping Address</label>
        <div class="col-sm-10">
            <input type="text" id="shipping_address" class="form-control-plaintext" value="{{ invoice.shipping_address }}" readonly>
        </div>
    </div>
    <div class="row">
        <label for="created_at" class="col-sm-2 col-form-label">Created_at</label>
        <div class="col-sm-10">
            <input type="text" id="created_at" class="form-control-plaintext" value=" {{ invoice.created_at }}" readonly>
        </div>
    </div>
    <div class="row">
        <label for="customer" class="col-sm-2 col-form-label">Customer</label>
        <div class="col-sm-10">
            <input type="text" id="customer" class="form-control-plaintext" value="{{ invoice.customer }}" readonly>
        </div>
    </div>
   
    <div class="row">
        <label for="product" class="col-sm-2 col-form-label">Products</label>
        <div class="col-sm-10">
            {% for product in invoice.product.all %}
                <input type="text" id="product" class="form-control-plaintext" value="{{ product }}" readonly>
            {% endfor %}
        </div>
    </div>
   
</form>
<a href="{% url "invoice:invoice_list" %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">All invoices</a>
<a href="{% url "invoice:htmltopdf" invoice.id %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Print Invoice</a>
</body>
</html>

invoice/templates/invoice/invoice_form.html
<!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
        <title>Add a new invoice</title>
      </head>
      <body>
        <div class="container">
            <h3 class="m-6 font-weight-bold text-primary">Insert Data for a new invoice</h3>

          <form  method="post">{% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Submit" />
            <a href="{% url "invoice:invoice_list" %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">All invoices</a>
          </form>
        </div>
      </body>
    </html>

invoice/templates/invoice/invoice_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Invoices</title>
  </head>
  <body>

	<div class="card shadow mb-4">
		<div class="card-header py-3">
            <h2 class="m-6 font-weight-bold text-primary">Invoices Management</h2>
            <a href="{% url "invoice:invoice_create" %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Create a new invoice</a>
            <a href="{% url 'logout' %}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Logout</a>


		</div>
		<div class="card-body">
			<div class="table-responsive">
				<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
					<thead>
						<tr>
                            <th>ID</th>
							<th>Address</th>
							<th>Created at</th>
                            <th>Customer</th>
							<th>View Details</th>

						</tr>
					</thead>
					
					<tbody>
						{% for invoice in invoices %}
							<tr>
                                <td>{{ invoice.id }}</td>
                                <td>{{ invoice.shipping_address }}</td>
								<td>{{ invoice.created_at }}</td>
                                <td>{{ invoice.customer }}</td>	
								<td><a href="{% url "invoice:invoice_detail" invoice.id %}">Details</a></td>

                            </tr>
						{% endfor %}
					</tbody>
                </table>
				<a href="{% url "invoice:customer_list" %}">All customers</a>
				<br>
				<a href="{% url "invoice:product_list" %}">All products</a>

			</div>
		</div>
	</div>                    
</body>
</html>

invoice/templates/product/product_detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Product Details</title>
  </head>
  <body>
<form>
   
    <div class="row">
        <label for="Name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" id="name" class="form-control-plaintext" value="{{ object.name }}" readonly>
        </div>
    </div>
    <div class="row">
        <label for="price" class="col-sm-2 col-form-label">Price</label>
        <div class="col-sm-10">
            <input type="text" id="price" class="form-control-plaintext" value=" {{ object.price }}" readonly>
        </div>
    </div>
    <div class="row">
        <label for="quantity" class="col-sm-2 col-form-label">Quantity</label>
        <div class="col-sm-10">
            <input type="text" id="quantity" class="form-control-plaintext" value="{{ object.quantity }}" readonly>
        </div>
    </div>
    
   
   
</form>
<a href="{% url "invoice:product_list" %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">All products</a>
</body>
</html>

invoice/templates/product/product_form.html
<!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
        <title>Add a new product</title>
      </head>
      <body>
        <div class="container">
          <h3 class="m-6 font-weight-bold text-primary">Insert Data for a new product</h3>
          <form  method="post">{% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Submit" />
            <a href="{% url "invoice:product_list" %}">All products</a>

          </form>
        </div>
      </body>
    </html>

invoice/templates/product/product_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Products</title>
  </head>
  <body>
    <div class="card shadow mb-4">
      <div class="card-header py-3">
              <h2 class="m-6 font-weight-bold text-primary">Products Management</h2>
              <a href="{% url "invoice:product_create" %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Add a new product</a>
              <a href="{% url 'logout' %}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Logout</a>
  
  
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>View Details</th>
                                    </tr>
                                    </thead>
                  
                               <tbody>
                                {% for product in object_list %}    
                                <tr>
                                <td>{{ product.id }}</td>  
                                <td>{{ product.name }}</td>  
                                <td>{{ product.price }}</td>  
                                <td>{{ product.quantity }}</td>  
                                <td><a href="{% url "invoice:product_detail" product.id %}">Details</a></td>
                                    </tr>
                                {% endfor %}
                  </tbody>
                        </table>
                        <a href="{% url "invoice:invoice_list" %}">All Invoices</a>
                        <br>
                        <a href="{% url "invoice:customer_list" %}">All Customers</a>

              </div>
            </div>
          </div>                    
        </body>
        </html>

       